server:
  port: 8014
spring:
  application:
    name: cam
  main:
    #允许循环依赖
    allow-circular-references: true
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/zray?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&autoReconnect=true
    username: root
    password: root

  swagger:
    enable: true
    groupName: 个人平台
    basePackage: com.zray.cam
    version: 1.0.0
    title: 长安某
    description: 长安某开发文档
    contactName: zray
    contactEmail:
    contactUrl: zray-data.com

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    #开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名
      logic-delete-field: flag
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 21
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 22